name: Bug Report
description: Let us know of an incompatibility with a mod or crashes etc.
title: "[Bug] Summary of bug"
labels: [bug]
body:
  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce?
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the mod are you on?
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    id: loader-version
    attributes:
      label: Fabric/Quilt Loader Version
      description: What version of the mod loader are you on?
      placeholder: 0.14.8 for 1.19.1
    validations:
      required: true

  - type: textarea
    id: logs-extra-context
    attributes:
      label: Logs or additional context
      description: Please copy and paste any relevant log output into a paste website such as [Hastebin](https://hst.sh) and then link them here. You may also give any additional information here too.

  - type: checkboxes
    id: has-not-been-reported
    attributes:
      label: Has not been reported.
      description: You made sure this bug hasn't already been reported.
      options:
        - label: I made sure this bug hasn't already been reported.
          required: true

  - type: checkboxes
    id: is-up-to-date
    attributes:
      label: Is on most update to date version.
      description: You made sure that you are on the most recent version of the fabric/quilt loader and the mod.
      options:
        - label: I made sure I am using the most up to date fabric/quilt loader and mod version.
          required: true
