name: Bug Status Check

on:
  push:
    branches:
      - '*'
    paths:
      - 'PATCHED.md'
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Check bug status

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pip requirements
        run: pip install requests packaging
      - name: Run script
        run: python scripts/check_bug_fixes.py
